"""Ubah enum JenisKelamin dari L/P ke Laki-Laki/Perempuan

Revision ID: 223c4d09fc1e
Revises: d08bc14632b2
Create Date: 2025-11-04 20:36:37.665316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '223c4d09fc1e'
down_revision = 'd08bc14632b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.ENUM('L', 'P'),
               type_=sa.Enum('LAKI_LAKI', 'PEREMPUAN', name='jeniskelamin'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.alter_column('jenis_kelamin',
               existing_type=sa.Enum('LAKI_LAKI', 'PEREMPUAN', name='jeniskelamin'),
               type_=mysql.ENUM('L', 'P'),
               existing_nullable=False)

    # ### end Alembic commands ###
