"""menambah tabel rujukan

Revision ID: 286494ff9863
Revises: 223c4d09fc1e
Create Date: 2026-01-08 10:05:26.457212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286494ff9863'
down_revision = '223c4d09fc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rujukan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('skrining_id', sa.BigInteger(), nullable=False),
    sa.Column('pasien_id', sa.BigInteger(), nullable=False),
    sa.Column('verified_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='statusrujukan'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['pasien.id'], ),
    sa.ForeignKeyConstraint(['skrining_id'], ['skrining.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skrining_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rujukan')
    # ### end Alembic commands ###
