"""initial migration

Revision ID: 99dca8348572
Revises: 
Create Date: 2025-10-28 06:25:47.992570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dca8348572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinsi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_provinsi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_provinsi')
    )
    op.create_table('kabupaten',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kabupaten', sa.String(length=100), nullable=False),
    sa.Column('provinsi_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_kabupaten')
    )
    op.create_table('kecamatan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kecamatan', sa.String(length=100), nullable=False),
    sa.Column('kabupaten_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['kabupaten_id'], ['kabupaten.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_kecamatan')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin_puskesmas', 'super_admin', name='userrole'), nullable=False),
    sa.Column('kecamatan_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('pasien',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kecamatan_id', sa.BigInteger(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('usia', sa.Integer(), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P', name='jeniskelamin'), nullable=False),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('pekerjaan', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('skrining',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pasien_id', sa.BigInteger(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('riwayat_kontak_tbc', sa.String(length=255), nullable=False),
    sa.Column('pernah_terdiagnosis_tbc', sa.String(length=255), nullable=False),
    sa.Column('pernah_berobat_tbc', sa.String(length=255), nullable=False),
    sa.Column('nama_obat_tbc', sa.String(length=255), nullable=True),
    sa.Column('pernah_beroobat_tbc_namun_tidak_tuntas', sa.String(length=255), nullable=False),
    sa.Column('malnutrisi', sa.String(length=255), nullable=False),
    sa.Column('merokok_atau_perokokok_pasif', sa.String(length=255), nullable=False),
    sa.Column('riwayat_diabetes_melitus_atau_kencing_manis', sa.String(length=255), nullable=False),
    sa.Column('lansia_lebih_dari_60_tahun', sa.String(length=255), nullable=False),
    sa.Column('ibu_hamil', sa.String(length=255), nullable=False),
    sa.Column('batuk', sa.String(length=255), nullable=False),
    sa.Column('bb_turun_tanpa_sebab_jelas_bb_tidak_naik_nafsu_makan_turun', sa.String(length=255), nullable=False),
    sa.Column('demam_yang_tidak_diketahui_penyebabnya', sa.String(length=255), nullable=False),
    sa.Column('badan_lemas', sa.String(length=255), nullable=False),
    sa.Column('berkesingat_malam_hari_tanpa_kegiatan', sa.String(length=255), nullable=False),
    sa.Column('sesak_napas_tanpa_nyeri_dada', sa.String(length=255), nullable=False),
    sa.Column('ada_pembengkakan_kelenjar_getah_bening_pada_leher_atau_ketiak', sa.String(length=255), nullable=False),
    sa.Column('tanggal_skrining', sa.Date(), nullable=False),
    sa.Column('hasil_deteksi', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'reviewed', name='skriningstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['pasien.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skrining')
    op.drop_table('pasien')
    op.drop_table('user')
    op.drop_table('kecamatan')
    op.drop_table('kabupaten')
    op.drop_table('provinsi')
    # ### end Alembic commands ###
