"""Remove unique constraint from nama_kecamatan

Revision ID: b2f27466c4b6
Revises: 99dca8348572
Create Date: 2025-11-02 19:20:07.504551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2f27466c4b6'
down_revision = '99dca8348572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kecamatan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nama_kecamatan'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('kecamatan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nama_kecamatan'), ['nama_kecamatan'], unique=True)

    # ### end Alembic commands ###
