version: '3.8'
services:
  backend-ai:
    build: ./backend_skrining_tbc
    ports:
      - "5000:5000"

  frontend-web:
    build: ./frontend_skrining_tbc
    ports:
      - "3000:3000"
    depends_on:
      - backend-ai
