services:
  # 1. DATABASE MYSQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: db_tbcheckv2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db

  # 3. BACKEND FLASK AI
  backend-ai:
    build: ./backend_skrining_tbc
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend_skrining_tbc:/app  <-- Dimatikan agar tidak menimpa file Docker
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1           # <-- Ditambahkan agar log langsung muncul
    depends_on:
      - db

  # 4. FRONTEND NEXT.JS
  frontend-web:
    build: ./frontend_skrining_tbc
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend_skrining_tbc:/app <-- Dimatikan agar folder .next tidak hilang
    #   - /app/node_modules
    depends_on:
      - backend-ai

volumes:
  db_data: